# Show debug messages
debug: false

# Delay between when events occur - for testing purposes may need to be set lower
OccurenceDelay: 60

# Worlds that events can occur in
Worlds: [world]

MoodInterval: 100