name: AlmightyNotch
author: ampayne2
main: ninja.amp.almightynotch.AlmightyNotchPlugin
version: '${project.version}'
commands:
  almightynotch:
    description: Admin commands for AlmightyNotch.
    aliases: [an, anotch, notch]
    permission: almightynotch.admin
    usage: /<command>