name: RandomEvents
main: me.ampayne2.randomevents.RandomEvents
version: '${project.version}'
commands:
  randomevents:
    description: Admin commands for RandomEvents.
    aliases: [re, revents]
    permission: randomevents.admin
    usage: /<command>